import type { Library, MediaItem } from '@raven/core'

export const library = (overrides: Partial<Library> = {}): Library => ({
  id: 2,
  name: 'Movies',
  paths: ['/media/Movies'],
  itemCount: 12,
  createdAt: '2026-09-27T00:00:00.000Z',
  scan: {
    state: 'idle',
    discovered: 12,
    processed: 12,
    startedAt: null,
    finishedAt: null,
    error: null,
  },
  settings: {
    saveProgress: true,
    pinned: true,
    sort: 'title',
    view: 'grid',
    groupBy: 'resolution',
    watchedPercent: 90,
  },
  ...overrides,
})

export const mediaItem = (overrides: Partial<MediaItem> = {}): MediaItem => ({
  id: 7,
  libraryId: 2,
  title: 'Busboys (2026)',
  fileName: 'Busboys (2026) 1080p WEBRip.mkv',
  folder: '',
  size: 1_609_721_462,
  container: 'mkv',
  duration: 5812.768,
  width: 1920,
  height: 1038,
  videoCodec: 'hevc',
  videoBitDepth: 10,
  hdr: false,
  audioCodec: 'aac',
  audioChannels: 6,
  bitrate: 2_215_000,
  thumbnail: 'ready',
  thumbnailVersion: 1,
  position: 0,
  favourite: false,
  addedAt: '2026-09-27T00:00:00.000Z',
  ...overrides,
})
